# ---------------------------------- Cluster -----------------------------------
cluster.name: wso2-app
# ------------------------------------ Node ------------------------------------
node.name: master-node-1
# ----------------------------------- Paths ------------------------------------
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
# ---------------------------------- Network -----------------------------------
network.host: 10.148.0.4
http.port: 9200
# --------------------------------- Discovery ----------------------------------
discovery.type: single-node
# ------------------------------------------------------------------------------
